name: C# Workflow

on:
  push:
   branches: ["main"]
  pull_request:
   branches: ["main"]

jobs:
  build:

   runs-on: windows-latest

   steps:

     - uses: actions/checkout@4
     
     - name: Setup .NET SDK
       uses: actions/setup-dotnet@v4
       with: 
           dotnet-version: '10.0'
           
     - name: Restore Dependencies
       run: dotnet restore
       
     - name: Build
       run: dotnet build --no-restore
       
    
     
     

     
